# Generated by Django 5.0.6 on 2024-08-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(choices=[('', 'Please select one'), ('API', 'API Integration'), ('CMS', 'CMS Integration'), ('eComm', 'eCommerce Web Design'), ('SEO', 'Site Optimization (SEO)'), ('wDev', 'Web Development'), ('wHost', 'Web Hosting'), ('Other', 'Other')], max_length=5)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
