# Generated by Django 5.0.6 on 2024-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('', 'Please select one'), ('API', 'API Integration'), ('CMS', 'CMS Integration'), ('eComm', 'eCommerce Web Design'), ('SEO', 'Site Optimization (SEO)'), ('webDev', 'Web Development'), ('webHost', 'Web Hosting'), ('Other', 'Other')], max_length=7),
        ),
    ]
