# Generated by Django 5.0.6 on 2024-09-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_firstname_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('API', 'API Integration'), ('CMS', 'CMS Integration'), ('eComm', 'eCommerce Web Design'), ('SEO', 'Site Optimization (SEO)'), ('webDev', 'Web Development'), ('webHost', 'Web Hosting'), ('Other', 'Other')], max_length=7),
        ),
    ]
