# Generated by Django 5.0.6 on 2024-09-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-id']},
        ),
    ]
