# Generated by Django 5.1.7 on 2025-04-01 13:51

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_alter_solution_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[800, 400], upload_to='solutions_image/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='tech_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
