# Generated by Django 5.1.7 on 2025-04-07 21:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_alter_solution_description_alter_solution_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
